### PR TITLE
Jest and examples tests installed and created

### PR DESCRIPTION
**Pull request by saralandis**
Let me know what you guys think before we merge into main

### CODE REVIEW

**Comment by saralandis** [comment]
@dworthm @jenniferjinyoungyang @PixelizedChell 

Let me know what you guys think of this. Questions?

Make sure you watch the rest of the testing video.

**Review by PixelizedChell — APPROVED** [review]
Looks good to me!

**Comment by saralandis** [comment]
I am still working on the continuous integration part.

**Comment by dworthm** [comment]
Looks good!

**Review by dworthm — APPROVED** [review]
Yay again

**Pull request merged**
