### PR TITLE
Added Routing for clean code and api calls

### PR DESCRIPTION
**Pull request by saralandis**
The server uses router for all api requests

Based on what the request is the router then references the specified api call in the controller file to be preformed. 

Let me know what you think. @PixelizedChell @dworthm @jenniferjinyoungyang

### CODE REVIEW

**Comment by saralandis** [comment]
@jenniferjinyoungyang  your api request would need to be moved from the server file into your controller file

**Review by PixelizedChell — APPROVED** [review]

**Review by dworthm — CHANGES_REQUESTED** [review]
Hey Sara. Thanks for setting this up. Can you take a quick look at a few things:
1) Nodemon crashed when I tried to run this. It didn't like the 
var controller = require('./controllers'); line in routes.js, despite that working fine in databases. It worked when I added the specific controller: var reviewsRequests = require('./controllers/reviewsRequests');
Maybe due to empty controllers? IF this doesn't cause problems on your end let me know.
2) I think the individual controller references should use reviewsRequests and not reviewRequests.
3) Can you change the APIkey import on row 3 of revewsRequests.js to go a directory higher?
4) It looks like Jennifer's original route in server.js has been removed but I don't see it in questionsRequests.js. I just want to make sure that doesn't get deleted.

**Comment by saralandis** [comment]
I corrected those problems Michael! Thank you for the attention to detail.

**Review by dworthm — APPROVED** [review]
Thanks for fixing those issues Sara.

**Pull request merged**
